# Generated by Django 2.2.11 on 2020-03-21 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='images/profile_pictures/no_img.jpg', upload_to='images/profile_pictures/')),
                ('profile_description', models.TextField(blank=True, max_length=500)),
                ('current_books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_books', to='club.Book')),
                ('discussion_groups_created', models.ForeignKey(blank=True, null=True, on_delete=models.SET('User deleted'), related_name='discussion_groups_created', to='club.DiscussionGroup')),
                ('discussion_groups_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.DiscussionGroup')),
                ('finished_books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_books', to='club.Book')),
                ('reading_groups_created', models.ForeignKey(blank=True, null=True, on_delete=models.SET('User deleted'), related_name='reading_groups_created', to='club.ReadingGroup')),
                ('reading_groups_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.ReadingGroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('want_to_read_books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='want_to_read_books', to='club.Book')),
            ],
        ),
    ]
