# Generated by Django 2.2.11 on 2020-04-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200406_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
