# Generated by Django 3.0.5 on 2020-04-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200416_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/no_img.jpg', max_length=800, upload_to='profile_pictures/'),
        ),
    ]
