# Generated by Django 3.0.5 on 2020-04-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200416_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='images/profile_pictures/no_img.jpg', max_length=800, upload_to='images/profile_pictures/'),
        ),
    ]
