# Generated by Django 2.2.11 on 2020-03-22 13:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('related_genres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Genre')),
            ],
            options={
                'ordering': ['genre_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=50)),
                ('book_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField()),
                ('book_release_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2020)])),
                ('book_language', models.CharField(blank=True, max_length=25, null=True)),
                ('book_cover_image', models.ImageField(default='images/book_covers/no_cover.png', upload_to='images/book_covers/')),
                ('book_isbn_number', models.CharField(max_length=17)),
                ('book_page_number', models.IntegerField()),
                ('book_read_pages', models.IntegerField(blank=True, null=True)),
                ('amazon_link', models.URLField(blank=True, null=True)),
                ('book_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Genre')),
                ('people_read_book', models.ManyToManyField(blank=True, related_name='people_read_book', to='account.Profile')),
                ('people_reading_book', models.ManyToManyField(blank=True, related_name='people_reading_book', to='account.Profile')),
                ('people_want_to_read_book', models.ManyToManyField(blank=True, related_name='people_want_to_read_book', to='account.Profile')),
            ],
            options={
                'ordering': ['book_name'],
            },
        ),
    ]
