# Generated by Django 2.2.11 on 2020-03-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200325_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='dislikes',
        ),
    ]
