# Generated by Django 2.2.11 on 2020-03-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_book_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_genre',
        ),
        migrations.AddField(
            model_name='book',
            name='book_categories',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
