# Generated by Django 2.2.11 on 2020-04-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20200406_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover_image',
            field=models.ImageField(default='images/book_covers/no_cover.png', max_length=500, upload_to='images/book_covers/'),
        ),
    ]
