# Generated by Django 3.0.5 on 2020-04-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20200406_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_isbn_number',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
