# Generated by Django 3.0.5 on 2020-04-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20200416_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover_image',
            field=models.ImageField(max_length=1000, upload_to='book_covers/'),
        ),
    ]
