# Generated by Django 3.0.5 on 2020-04-16 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_auto_20200416_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_release_year',
            field=models.IntegerField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2020)]),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=150),
        ),
    ]
