# Generated by Django 3.0.5 on 2020-04-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_auto_20200416_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover_image',
            field=models.ImageField(default='images/book_covers/no_cover.png', max_length=1000, upload_to='images/book_covers/'),
        ),
    ]
