# Generated by Django 2.2.11 on 2020-03-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20200321_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussiongroup',
            name='group_members',
            field=models.ManyToManyField(related_name='discussion_group_members', to='club.Profile'),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='group_members',
            field=models.ManyToManyField(related_name='reading_group_members', to='club.Profile'),
        ),
    ]
