# Generated by Django 2.2.11 on 2020-03-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20200322_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='group_members',
            field=models.ManyToManyField(blank=True, related_name='reading_group_members', to='club.Profile'),
        ),
    ]
