# Generated by Django 2.2.11 on 2020-03-22 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20200322_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='related_genres',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='discussiongroup',
            name='current_book',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Book'),
        ),
        migrations.AlterField(
            model_name='discussiongroup',
            name='group_creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_group_creator', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='discussiongroup',
            name='group_members',
            field=models.ManyToManyField(related_name='discussion_group_members', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='current_book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Book'),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='group_creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_group_creator', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='group_members',
            field=models.ManyToManyField(blank=True, related_name='reading_group_members', to='account.Profile'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
