# Generated by Django 2.2.11 on 2020-03-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_discussioncomment_readingcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussioncomment',
            old_name='active',
            new_name='disabled',
        ),
        migrations.RenameField(
            model_name='readingcomment',
            old_name='active',
            new_name='disabled',
        ),
    ]
