# Generated by Django 2.2.11 on 2020-03-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_auto_20200325_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussioncomment',
            old_name='group',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='readingcomment',
            old_name='group',
            new_name='club',
        ),
    ]
