# Generated by Django 2.2.11 on 2020-03-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_auto_20200325_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussioncomment',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingcomment',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingcomment',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
