# Generated by Django 2.2.11 on 2020-03-25 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_auto_20200325_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussiongroup',
            name='group_creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_group_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussiongroup',
            name='group_members',
            field=models.ManyToManyField(blank=True, related_name='discussion_group_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='group_creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_group_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='group_members',
            field=models.ManyToManyField(blank=True, related_name='reading_group_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
