# Generated by Django 2.2.11 on 2020-04-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0017_auto_20200326_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussiongroup',
            name='group_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='group_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='recommendationgroup',
            name='group_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
