# Generated by Django 2.2.11 on 2020-04-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0018_auto_20200406_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussiongroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recommendationgroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
