# Generated by Django 3.0.5 on 2020-04-07 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20200406_1152'),
        ('club', '0019_auto_20200406_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussiongroup',
            name='current_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_group_book', to='book.Book'),
        ),
    ]
