# Generated by Django 3.0.5 on 2020-04-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0020_auto_20200407_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussiongroup',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recommendationgroup',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
    ]
