# Generated by Django 3.0.5 on 2020-04-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0024_auto_20200416_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussiongroup',
            name='group_image',
            field=models.ImageField(max_length=1000, upload_to='group_pictures/'),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='group_image',
            field=models.ImageField(max_length=1000, upload_to='group_pictures/'),
        ),
        migrations.AlterField(
            model_name='recommendationgroup',
            name='group_image',
            field=models.ImageField(max_length=1000, upload_to='group_pictures/'),
        ),
    ]
