# Generated by Django 3.0.5 on 2020-04-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0026_auto_20200416_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussiongroup',
            name='group_name',
            field=models.CharField(max_length=101),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='group_name',
            field=models.CharField(max_length=101),
        ),
        migrations.AlterField(
            model_name='recommendationgroup',
            name='group_name',
            field=models.CharField(max_length=101),
        ),
    ]
