# Generated by Django 3.0.5 on 2020-04-16 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0019_auto_20200416_1113'),
        ('club', '0028_auto_20200416_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussiongroup',
            name='current_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_group_book', to='book.Book'),
        ),
        migrations.AlterField(
            model_name='discussiongroup',
            name='group_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_group_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussiongroup',
            name='group_members',
            field=models.ManyToManyField(blank=True, related_name='discussion_group_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='current_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_group_book', to='book.Book'),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='group_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_group_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='group_members',
            field=models.ManyToManyField(blank=True, related_name='reading_group_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='reading_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
