# Generated by Django 3.0.5 on 2020-04-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0030_auto_20200416_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussiongroup',
            name='group_image',
            field=models.ImageField(default='images/group_pictures/no_img.png', upload_to='images/group_pictures/'),
        ),
        migrations.AlterField(
            model_name='discussiongroup',
            name='is_private_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discussiongroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='group_image',
            field=models.ImageField(default='images/group_pictures/no_img.png', upload_to='images/group_pictures/'),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='is_private_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recommendationgroup',
            name='group_image',
            field=models.ImageField(default='images/group_pictures/no_img.png', upload_to='images/group_pictures/'),
        ),
        migrations.AlterField(
            model_name='recommendationgroup',
            name='is_private_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recommendationgroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
