# Generated by Django 3.0.5 on 2020-04-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0032_auto_20200416_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinggroup',
            name='current_book_current_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='current_book_page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
