# Generated by Django 3.0.5 on 2020-04-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0033_auto_20200417_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussiongroup',
            name='group_image',
            field=models.ImageField(default='images/group_pictures/no_img.jpg', max_length=10000, upload_to='images/group_pictures/'),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='group_image',
            field=models.ImageField(default='images/group_pictures/no_img.jpg', max_length=10000, upload_to='images/group_pictures/'),
        ),
        migrations.AlterField(
            model_name='recommendationgroup',
            name='group_image',
            field=models.ImageField(default='images/group_pictures/no_img.jpg', max_length=10000, upload_to='images/group_pictures/'),
        ),
    ]
