# Generated by Django 3.0.5 on 2020-04-20 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20200416_1200'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0035_auto_20200417_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussioncomment',
            name='profile',
            field=models.ForeignKey(default=1, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
        migrations.AddField(
            model_name='readingcomment',
            name='profile',
            field=models.ForeignKey(default=1, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='current_goal_achieved',
            field=models.ManyToManyField(blank=True, related_name='current_goal_achieved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='current_goal_reaching',
            field=models.ManyToManyField(blank=True, related_name='current_goal_reaching', to=settings.AUTH_USER_MODEL),
        ),
    ]
